[package]
name = "versatile-data"
version = "0.6.0"
edition = "2021"

description = "A library for databases that has convenient datasets that group together commonly used fields and gives you the flexibility to create your own fields."

repository = "https://github.com/OdenShirataki/versatile-data"

keywords = ["avltree","database","Index","library"]
license = "MIT/Apache-2.0"

[dependencies]
libc="0.2"
natord="1.0"
chrono="0.4"

file_mmap={ path="../file_mmap" , version="0.2" }
indexed_data_file={ path="../indexed_data_file" , version="0.6" }
strings_set_file={ path="../strings_set_file" , version="0.1" }

[dependencies.uuid]
version = "1.0"
features = [
    "v4",
    "fast-rng",
    "macro-diagnostics",
]