[package]
name = "versatile-data"
version = "0.33.1"
edition = "2021"

description = "A library for databases that has convenient datasets that group together commonly used fields and gives you the flexibility to create your own fields."

repository = "https://github.com/OdenShirataki/versatile-data"

keywords = ["avltree","database","Index","library"]
license = "MIT/Apache-2.0"

[dependencies]
natord="1.0"
chrono="0.4"

file_mmap="0.4"
idx_sized="0.10"
various_data_file="0.3"

[dependencies.uuid]
version = "1.0"
features = [
    "v4",
    "fast-rng",
    "macro-diagnostics",
]