[package]
name = "versatile-data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc="0.2"
natord="1.0"

file_mmap={ path="../file_mmap" , version="0.1" }
indexed_data_file={ path="../indexed_data_file" , version="0.6" }
strings_set_file={ path="../strings_set_file" , version="0.1" }
